const jobListings = [
  {
    id: 1,
    name: 'Front End Developer',
    company: 'Google',
    skills: ['React', 'TypeScript', 'CSS'],
    status: 'applied',
    applied: true,
  },
  {
    id: 2,
    name: 'Back End Developer',
    company: 'Amazon',
    skills: ['Node.js', 'Express', 'MongoDB'],
    status: 'recieved',
    applied: true,
  },
  {
    id: 3,
    name: 'Full Stack Developer',
    company: 'Facebook',
    skills: ['React', 'Node.js', 'GraphQL'],
    status: 'proposal',
    applied: true,
  },
  {
    id: 4,
    name: 'Webflow Developer',
    company: 'Webflow',
    skills: ['Webflow', 'JavaScript', 'HTML'],
    status: 'rejected',
    applied: false,
  },
  {
    id: 5,
    name: 'Front End Developer',
    company: 'Microsoft',
    skills: ['Angular', 'TypeScript', 'SCSS'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 6,
    name: 'Front End Developer',
    company: 'Google',
    skills: ['React', 'TypeScript', 'CSS'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 7,
    name: 'Back End Developer',
    company: 'Amazon',
    skills: ['Node.js', 'Express', 'MongoDB'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 8,
    name: 'Full Stack Developer',
    company: 'Facebook',
    skills: ['React', 'Node.js', 'GraphQL'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 9,
    name: 'Webflow Developer',
    company: 'Webflow',
    skills: ['Webflow', 'JavaScript', 'HTML'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 10,
    name: 'Front End Developer',
    company: 'Microsoft',
    skills: ['Angular', 'TypeScript', 'SCSS'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 11,
    name: 'Front End Developer',
    company: 'Google',
    skills: ['React', 'TypeScript', 'CSS'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 12,
    name: 'Back End Developer',
    company: 'Amazon',
    skills: ['Node.js', 'Express', 'MongoDB'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 13,
    name: 'Full Stack Developer',
    company: 'Facebook',
    skills: ['React', 'Node.js', 'GraphQL'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 14,
    name: 'Webflow Developer',
    company: 'Webflow',
    skills: ['Webflow', 'JavaScript', 'HTML'],
    status: 'not applied',
    applied: false,
  },
  {
    id: 15,
    name: 'Front End Developer',
    company: 'Microsoft',
    skills: ['Angular', 'TypeScript', 'SCSS'],
    status: 'not applied',
    applied: false,
  },
];

export default jobListings;
